site_name: CME World 
site_url: https://wiki.cmeworld.fun 

theme:
  name: material
  language: ru
  features:
    - navigation.indexes
    - navigation.tabs

  logo: assets/logo.png
  favicon: assets/CME World logo border.png
  palette:
    - scheme: slate
      primary: deep purple  # Ğ¼Ğ¾Ğ¶Ğ½Ğ¾ Ğ¾ÑÑ‚Ğ°Ğ²Ğ¸Ñ‚ÑŒ Ğ»ÑĞ±Ğ¾Ğ¹
      accent: deep purple
  font:
    code: Roboto mono

  custom_dir: overrides
extra_css:
  - css/main.css

extra_javascript:
  - 'js/main.js'




extra:
  homepage: https://www.cmeworld.fun # Ğ¾Ğ¿Ñ†Ğ¸Ğ¾Ğ½Ğ°Ğ»ÑŒĞ½Ğ¾

plugins: []



markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  
nav:
  - ğŸ  Ğ“Ğ»Ğ°Ğ²Ğ½Ğ°Ñ:
     - ğŸ  Ğ“Ğ»Ğ°Ğ²Ğ½Ğ°Ñ: index.md
     - ğŸ“– ĞŸÑ€Ğ°Ğ²Ğ¸Ğ»Ğ°: Rules.md
     - ğŸ“œ ĞŸĞ¾Ğ»ĞµĞ·Ğ½Ñ‹Ğµ Ğ¼Ğ¾Ğ´Ñ‹: Dependencies.md 
  - ğŸ“ƒ Ğ’Ğ¸ĞºĞ¸:
    - ğŸ  Ğ“Ğ»Ğ°Ğ²Ğ½Ğ°Ñ: Wiki/index.md 
    - ğŸ™ Simple Voice Chat: Wiki/Simple-Voice-Chat.md
    - ğŸ›¡ Core Protect: Wiki/Core-Protect.md
    - ğŸ—º BlueMap: Wiki/Bluemap.md
    - ğŸ˜€ Emotecraft: Wiki/Emotecraft.md
    - ğŸ¨ MC Paint:
      - ğŸ  Ğ“Ğ»Ğ°Ğ²Ğ½Ğ°Ñ: Wiki/MC-Paint/MC-Paint.md
      - ğŸª› Ğ‘Ğ»Ğ¾ĞºĞ¸: Wiki/MC-Paint/Additions.md
      - ğŸ¨ Ğ¡Ñ‚ÑƒĞ´Ğ¸Ñ: Wiki/MC-Paint/Studio.md
      - ğŸª£ Ğ’ĞµĞ´Ñ€Ğ¾ Ñ ĞºÑ€Ğ°ÑĞºĞ¾Ğ¹: Wiki/MC-Paint/Paint-Bucket.md
      - ğŸ”§ Ğ˜Ğ½ÑÑ‚Ñ€ÑƒĞ¼ĞµĞ½Ñ‚Ñ‹: Wiki/MC-Paint/Custom-Painting-Modifiers.md
      - ğŸ“¤ ĞĞ±Ğ¼ĞµĞ½ ĞºĞ°Ñ€Ñ‚Ğ¸Ğ½Ğ°Ğ¼Ğ¸: Wiki/MC-Paint/Sharing-paintings.md
    - ğŸ›  ĞšĞ°ÑÑ‚Ğ¾Ğ¼Ğ½Ñ‹Ğµ ĞºÑ€Ğ°Ñ„Ñ‚Ñ‹: Wiki/Custom-craft.md
    - ğŸ‘• Ğ¡Ğ¸ÑÑ‚ĞµĞ¼Ğ° ÑĞºĞ¸Ğ½Ğ¾Ğ²: Wiki/Skins-Resrtorer.md
    - ğŸ‘¨â€ğŸŒ¾ ĞĞ¿Ñ‚Ğ¸Ğ¼Ğ¸Ğ·Ğ°Ñ†Ğ¸Ñ Ğ¶Ğ¸Ñ‚ĞµĞ»ĞµĞ¹: Wiki/Vilager-Trade.md
