site_name: CME World 
site_url: https://wiki.cmeworld.fun 

theme:
  name: material
  language: ru
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.expand

  logo: assets/logo.png
  palette:
    - scheme: slate
      primary: deep purple  # можно оставить любой
      accent: deep purple
      dark: true
  font:
    code: Roboto mono



extra:
  homepage: https://www.cmeworld.fun # опционально

plugins:
  - search


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  
nav:
  - Главная: index.md
  - Вики:
    - Главная: Wiki/Wiki.md 
    - Simple Voice Chat: Wiki/Simple-Voice-Chat.md
    - Core Protect: Wiki/Core-Protect.md
    - BlueMap: Wiki/Bluemap.md
    - Emotecraft: Wiki/Emotecraft.md
    - Кастомные крафты: Wiki/Custom-craft.md
    - Система скинов: Wiki/Skins-Resrtorer.md
    - Оптимизация жителей: Wiki/Vilager-Trade.md
